export enum ProgrammingLanguages {
  JavaScript = 'JavaScript',
  Python = 'Python',
  Java = 'Java',
  CSHARP = 'C#',
  CPLUSPLUS = 'C++',
  PHP = 'PHP',
  TypeScript = 'TypeScript',
  Ruby = 'Ruby',
  Swift = 'Swift',
  Go = 'Go',
  Kotlin = 'Kotlin',
  Rust = 'Rust',
  Dart = 'Dart',
  Scala = 'Scala',
  ShellScripting = 'Shell Scripting',
  Perl = 'Perl',
  ObjectiveC = 'Objective-C',
  R = 'R',
  Elixir = 'Elixir',
  Haskell = 'Haskell',
}
