export enum ProgrammingLanguages {
  JavaScript = 'JavaScript',
  Python = 'Python',
  Java = 'Java',
  CSHARP = 'C#',
  CPLUSPLUS = 'C++',
  PHP = 'PHP',
  TypeScript = 'TypeScript',
  Ruby = 'Ruby',
  Swift = 'Swift',
  Go = 'Go',
  Kotlin = 'Kotlin',
  Rust = 'Rust',
  Dart = 'Dart',
  Scala = 'Scala',
  ShellScripting = 'Shell Scripting',
  Perl = 'Perl',
  ObjectiveC = 'Objective-C',
  R = 'R',
  Elixir = 'Elixir',
  Haskell = 'Haskell',
}

export const ProgrammingLanguagesOptions: { value: string; label: string }[] = [
  {
    value: ProgrammingLanguages.JavaScript,
    label: ProgrammingLanguages.JavaScript,
  },
  { value: ProgrammingLanguages.Python, label: ProgrammingLanguages.Python },
  { value: ProgrammingLanguages.Java, label: ProgrammingLanguages.Java },
  { value: ProgrammingLanguages.CSHARP, label: ProgrammingLanguages.CSHARP },
  {
    value: ProgrammingLanguages.CPLUSPLUS,
    label: ProgrammingLanguages.CPLUSPLUS,
  },
  { value: ProgrammingLanguages.PHP, label: ProgrammingLanguages.PHP },
  {
    value: ProgrammingLanguages.TypeScript,
    label: ProgrammingLanguages.TypeScript,
  },
  { value: ProgrammingLanguages.Ruby, label: ProgrammingLanguages.Ruby },
  { value: ProgrammingLanguages.Swift, label: ProgrammingLanguages.Swift },
  { value: ProgrammingLanguages.Go, label: ProgrammingLanguages.Go },
  { value: ProgrammingLanguages.Kotlin, label: ProgrammingLanguages.Kotlin },
  { value: ProgrammingLanguages.Rust, label: ProgrammingLanguages.Rust },
  { value: ProgrammingLanguages.Dart, label: ProgrammingLanguages.Dart },
  { value: ProgrammingLanguages.Scala, label: ProgrammingLanguages.Scala },
  {
    value: ProgrammingLanguages.ShellScripting,
    label: ProgrammingLanguages.ShellScripting,
  },
  { value: ProgrammingLanguages.Perl, label: ProgrammingLanguages.Perl },
  {
    value: ProgrammingLanguages.ObjectiveC,
    label: ProgrammingLanguages.ObjectiveC,
  },
  { value: ProgrammingLanguages.R, label: ProgrammingLanguages.R },
  { value: ProgrammingLanguages.Elixir, label: ProgrammingLanguages.Elixir },
  {
    value: ProgrammingLanguages.Haskell,
    label: ProgrammingLanguages.Haskell,
  },
];
